server:
  port: 8443
  ssl:
    key-alias: tomcat
    key-store: server.keystore
    key-store-password: 123456
    key-store-type: JKS
    enabled: true
http:
  port: 8080
#日志级别
logging:
  level:
    root: info